events {}

http {
  upstream api_upstream {
    server api:3000;
  }

  upstream search_upstream {
    server search:4000;
  }

  server {
    listen 80;

    location /api/ {
      proxy_pass http://api_upstream/;
    }

    location /search/ {
      proxy_pass http://search_upstream/;
    }

    location /health {
      default_type application/json;
      return 200 '{"status":"ok","gateway":"nginx"}';
    }
  }
}
